/**
 * Lists every editable customer-facing email template for the superadmin
 * editor (app/superadmin/email-templates). Each entry's `id` MUST match the
 * templateId string passed to renderTemplate() at the real send call site
 * (grep for it to find the site) -- that's what links an override to an
 * actual email.
 *
 * `sampleHtml` is what the editor shows as a starting point when a template
 * has never been customized (no saved override yet). For the onboarding,
 * trial, and waitlist-nurture sequences it's generated by calling the real
 * shared functions with sample data, so it can never drift from what's
 * actually sent. For the ~20 standalone templates (one-off HTML inline at
 * their call site, not a shared function), sampleHtml is a copy of that
 * default, kept here only for the editor's starting point -- if you change
 * the inline default at a call site, update its copy here too, or the
 * editor's "start from current default" view goes stale for anyone who
 * hasn't customized that template yet. This never affects what's actually
 * sent: the real send path always reads its own local default directly.
 */
import { ONBOARDING_EMAILS } from '@/lib/onboarding-emails'
import { TRIAL_EMAILS, USER_EMAILS } from '@/lib/trial-emails'
import { getWaitlistNurtureEmail } from '@/lib/waitlist-nurture'

export interface RegisteredTemplate {
  id: string
  label: string
  group: string
  /** Token names usable as {{token}} in this template's HTML. */
  params: string[]
  /** Sample values for every param, used to render the live preview. */
  sampleParams: Record<string, string>
  /** Starting content when nothing has been customized yet. */
  sampleHtml: string
}

const S = {
  firstName:    'Sarah',
  displayName:  'Sarah',
  name:         'Sarah',
  orgName:      'Sunrise Care Home',
  expiryDate:   '30 September 2026',
  deletionDate: '14 October 2026',
  price:        '£75',
  when:         '16 September 2026 at 14:32',
  kloeTitle:    'Safe: Safeguarding Systems, Processes and Practices',
  kloUrl:       'https://portal.alwaysready.uk/dashboard/kloes/sample-id',
  dueDate:      '23 September 2026',
  daysLeft:     '5',
  staffName:    'James Mitchell',
  fieldLabel:   'DBS Check',
  message:      'Thanks for flagging this. Evidence uploads accept .pdf, .docx, .xlsx, .jpg, .jpeg, and .png files.',
  reference:    'AR-0042',
  subject:      'Unable to upload evidence documents',
  followUpText: `If your issue has not been fully resolved or you have a follow-up question, please open a new support ticket from the <strong>Support</strong> section inside the platform and we'll be happy to help.`,
  adminName:    'Sarah',
  loginUrl:     'https://portal.alwaysready.uk/login',
  adminEmail:   'sarah@sunrisecarehome.co.uk',
  adminPassword: 'TempPass-8f2a1c',
  trialExpiry:  '30 September 2026',
  charityNote:  '',
  setupLink:    'https://portal.alwaysready.uk/account/setup?token=example',
  upgradeUrl:   'https://portal.alwaysready.uk/upgrade',
  notificationsList: '<li style="margin:0 0 4px">KLOE &amp; HR review reminders</li>',
  readinessPct: '78',
  reportDate:   '16 September 2026',
}

export function getRegistry(): RegisteredTemplate[] {
  const entries: RegisteredTemplate[] = []

  // ── Onboarding sequence (18): lib/onboarding-emails.ts ──────────────────
  for (const email of ONBOARDING_EMAILS) {
    entries.push({
      id:           `onboarding_${email.weekId}`,
      label:        `Onboarding ${email.weekId.replace('week_', 'week ')}: ${email.subject}`,
      group:        'Onboarding sequence',
      params:       ['firstName'],
      sampleParams: { firstName: S.firstName },
      sampleHtml:   email.body(S.firstName),
    })
  }

  // ── Trial sequence (7): lib/trial-emails.ts ──────────────────────────────
  for (const email of TRIAL_EMAILS) {
    entries.push({
      id:           `trial_${email.dayKey}`,
      label:        `Trial ${email.dayKey.replace('day_', 'day ')}: ${email.subject}`,
      group:        'Trial sequence',
      params:       ['firstName', 'expiryDate', 'price'],
      sampleParams: { firstName: S.firstName, expiryDate: S.expiryDate, price: S.price },
      sampleHtml:   email.bodyHtml(S.firstName, S.expiryDate, S.price),
    })
  }

  // ── Invited-user check-ins (2): lib/trial-emails.ts ──────────────────────
  for (const email of USER_EMAILS) {
    entries.push({
      id:           `user_${email.dayKey}`,
      label:        `Team member ${email.dayKey.replace('day_', 'day ')}: ${email.subject}`,
      group:        'Invited team member check-ins',
      params:       ['firstName', 'orgName'],
      sampleParams: { firstName: S.firstName, orgName: S.orgName },
      sampleHtml:   email.bodyHtml(S.firstName, S.orgName),
    })
  }

  // ── Waitlist nurture (10): lib/waitlist-nurture.ts ───────────────────────
  for (let i = 1; i <= 10; i++) {
    const email = getWaitlistNurtureEmail(i, S.firstName)
    if (!email) continue
    entries.push({
      id:           `waitlist_nurture_${i}`,
      label:        `Waitlist ${i}: ${email.subject}`,
      group:        'Waitlist nurture sequence',
      params:       ['firstName'],
      sampleParams: { firstName: S.firstName },
      sampleHtml:   email.bodyHtml,
    })
  }

  // ── Standalone transactional/marketing templates ─────────────────────────
  // Each id below must match the templateId at its real renderTemplate()
  // call site (grep the codebase for the id to find it).

  entries.push({
    id: 'blog_subscribe_confirmation',
    label: 'Blog subscription confirmation',
    group: 'Website',
    params: ['displayName'],
    sampleParams: { displayName: S.displayName },
    sampleHtml: `
        <p>
          Thanks for subscribing to the AlwaysReady blog, ${S.displayName}. We cover CQC inspection readiness,
          compliance, and governance for care providers. New posts will arrive straight to your inbox.
        </p>
        <p>
          You can browse everything we've published so far at
          <a href="https://alwaysready.uk/blog" style="color:#014D4E">alwaysready.uk/blog</a>.
        </p>
      `,
  })

  entries.push({
    id: 'blog_subscribe_confirmation_waitlist',
    label: 'Blog subscription confirmation (from waitlist signup)',
    group: 'Website',
    params: ['displayName'],
    sampleParams: { displayName: S.displayName },
    sampleHtml: `
        <p>You're now subscribed to the AlwaysReady blog, ${S.displayName}. We'll send you practical tips,
           sector updates, and inspection-readiness guidance, straight to your inbox.</p>
        <p>You can unsubscribe at any time by clicking the unsubscribe link in any of our emails.</p>
      `,
  })

  entries.push({
    id: 'contact_auto_responder',
    label: "Contact form auto-responder ('We've received your message')",
    group: 'Website',
    params: ['name'],
    sampleParams: { name: S.name },
    sampleHtml: `
      <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
        Thank you for getting in touch, ${S.name}. We have received your message and will get back to you shortly.
      </p>
      <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
        While you wait, you may find the answer you&rsquo;re looking for in our
        <a href="https://alwaysready.uk/helpcentre" style="color:#014D4E">Help Centre</a>.
        If you prefer to ask a question in your own words, our AI platform assistant, Ara, is available in the bottom-right corner of most pages on the AlwaysReady website.
      </p>
    `,
  })

  entries.push({
    id: 'waitlist_signup_confirmation',
    label: "Waitlist signup confirmation (non-nurture leads)",
    group: 'Website',
    params: ['displayName'],
    sampleParams: { displayName: S.displayName },
    sampleHtml: `
          <p>Thank you for joining the AlwaysReady waitlist, ${S.displayName}. You're in good company.</p>
          <p>We're building AlwaysReady around the new CQC Adult Social Care Assessment Framework,
             and we'll open to new customers as soon as the framework is published.
             When that happens, you'll be the first to know.</p>
          <p>In the meantime, if you have any questions about the platform, feel free to reply
             to this email or visit
             <a href="https://alwaysready.uk/contact" style="color:#014D4E">alwaysready.uk/contact</a>.</p>
        `,
  })

  entries.push({
    id: 'trial_signup_welcome',
    label: 'Trial signup welcome (set your password)',
    group: 'Trial',
    params: ['firstName', 'serviceName', 'expiry', 'setupLink'],
    sampleParams: { firstName: S.firstName, serviceName: S.orgName, expiry: S.expiryDate, setupLink: S.setupLink },
    sampleHtml: `
      <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#1a1a1a">
        Your 14-day free trial of AlwaysReady is ready, ${S.firstName}. Click the button below to
        set your password and get straight into your account.
      </p>

      <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#1a1a1a">
        <strong style="color:#014D4E">${S.orgName}</strong> has been configured
        to your service type using the CQC Adult Social Care Assessment Framework. You can
        start recording your compliance position, uploading evidence, and building your
        inspection readiness straight away.
      </p>

      <p style="margin:0 0 32px">
        <a href="${S.setupLink}"
           style="display:inline-block;background-color:#014D4E;color:#ffffff;
                  padding:14px 28px;border-radius:6px;font-size:15px;
                  font-weight:600;text-decoration:none">
          Set your password and get started &rarr;
        </a>
      </p>

      <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#1a1a1a">
        Your trial runs until <strong>${S.expiryDate}</strong>.
        If you have any questions, use the <strong>Support</strong> tab inside
        the platform and we will get back to you shortly.
      </p>

      <p style="margin:0;font-size:12px;color:#aaa;line-height:1.6">
        If the button above does not work, copy and paste this link into your browser:<br>
        <a href="${S.setupLink}" style="color:#014D4E;word-break:break-all">${S.setupLink}</a>
      </p>
    `,
  })

  entries.push({
    id: 'trial_lapsed',
    label: 'Trial lapsed (never subscribed)',
    group: 'Trial',
    params: ['firstName', 'expiryDate', 'deletionDate', 'upgradeUrl'],
    sampleParams: { firstName: S.firstName, expiryDate: S.expiryDate, deletionDate: S.deletionDate, upgradeUrl: S.upgradeUrl },
    sampleHtml: `
          <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
            Your AlwaysReady trial ended on ${S.expiryDate}, ${S.firstName}. The KLOEs you rated, evidence you
            uploaded, and any HR records or team settings you created are all still there,
            exactly as you left them.
          </p>
          <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
            Your data is available to download until <strong>${S.deletionDate}</strong>, after
            which it will be permanently deleted. If you'd like to keep access and continue
            building your inspection readiness, subscribing takes less than two minutes;
            everything carries over immediately.
          </p>
          <p style="margin:0 0 32px">
            <a href="${S.upgradeUrl}"
               style="display:inline-block;background-color:#014D4E;color:#ffffff;padding:14px 28px;border-radius:6px;font-size:15px;font-weight:600;text-decoration:none">
              Subscribe and continue &rarr;
            </a>
          </p>
          <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
            If there's anything we could have done better, we'd genuinely welcome hearing from
            you, just reply to this email. Whatever you decide, thank you for taking the time
            to try AlwaysReady.
          </p>
        `,
  })

  entries.push({
    id: 'subscription_active',
    label: 'Subscription now active',
    group: 'Billing',
    params: ['firstName'],
    sampleParams: { firstName: S.firstName },
    sampleHtml: `
              <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
                Thank you, ${S.firstName}. Your subscription is now active and your account will continue without interruption.
              </p>
              <p style="margin:0 0 32px;font-size:15px;line-height:1.7;color:#1a1a1a">
                We are delighted to have you on board. If there is anything we can do to help you
                get the most from AlwaysReady, please use the <strong>Support</strong> tab inside the platform.
              </p>
              <p style="margin:0 0 32px">
                <a href="https://portal.alwaysready.uk/dashboard"
                   style="display:inline-block;background-color:#014D4E;color:#ffffff;padding:14px 28px;border-radius:6px;font-size:15px;font-weight:600;text-decoration:none">
                  Go to your dashboard &rarr;
                </a>
              </p>
            `,
  })

  entries.push({
    id: 'subscription_ended',
    label: 'Subscription ended (download your data)',
    group: 'Billing',
    params: ['orgName', 'deletionDate'],
    sampleParams: { orgName: S.orgName, deletionDate: S.deletionDate },
    sampleHtml: `
                <p>Your AlwaysReady subscription for <strong>${S.orgName}</strong> has ended.</p>
                <p>Your data is safe and available to download until <strong>${S.deletionDate}</strong>.
                After that date, it will be permanently deleted.</p>
                <p>To download your data, log in at
                <a href="https://portal.alwaysready.uk/login" style="color:#014D4E">portal.alwaysready.uk</a>
                and use the download buttons on the page shown.</p>
                <p>If you'd like to resubscribe and keep your data, you can do so from the same page.</p>
              `,
  })

  entries.push({
    id: 'password_changed',
    label: 'Password changed confirmation',
    group: 'Account',
    params: ['when'],
    sampleParams: { when: S.when },
    sampleHtml: `
        <p>Your AlwaysReady password was successfully changed on <strong>${S.when}</strong>.</p>
        <p style="color:#555;font-size:14px">If you made this change, there is nothing further for you to do. If it wasn't you, change your password immediately or contact your local admin manager.</p>
      `,
  })

  entries.push({
    id: 'kloe_assigned',
    label: 'KLOE assigned to you',
    group: 'Platform',
    params: ['firstName', 'kloeTitle', 'kloUrl'],
    sampleParams: { firstName: S.firstName, kloeTitle: S.kloeTitle, kloUrl: S.kloUrl },
    sampleHtml: `
            <p style="margin:0 0 16px">
              You've been assigned a KLOE that needs your attention, ${S.firstName}:
            </p>
            <p style="margin:0 0 24px;padding:16px 20px;background:#f0fdfb;border-left:4px solid #00b8a6;border-radius:4px;font-weight:600;color:#014D4E">
              ${S.kloeTitle}
            </p>
            <p style="margin:0 0 24px">
              Log in to AlwaysReady to review the KLOE(s) you have been assigned, upload evidence, and update your progress.
            </p>
            <p style="margin:0 0 32px">
              <a href="${S.kloUrl}"
                 style="display:inline-block;background:#014D4E;color:#ffffff;font-weight:600;font-size:15px;padding:12px 24px;border-radius:6px;text-decoration:none">
                View KLOE →
              </a>
            </p>
            <p style="margin:0;font-size:13px;color:#666">
              If you have any questions about what's needed, speak to your admin.
            </p>
          `,
  })

  entries.push({
    id: 'kloe_review_due_soon',
    label: 'KLOE review due soon',
    group: 'Platform',
    params: ['kloeTitle', 'dueDate', 'daysLeft'],
    sampleParams: { kloeTitle: S.kloeTitle, dueDate: S.dueDate, daysLeft: S.daysLeft },
    sampleHtml: `
    <p style="margin:0 0 16px">
      This is a reminder that your KLOE review is due in <strong>${S.daysLeft} days</strong>.
    </p>
    <table style="width:100%;border-collapse:collapse;margin:0 0 24px">
      <tr>
        <td style="padding:12px 16px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px">
          <p style="margin:0 0 4px;font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">KLOE</p>
          <p style="margin:0;font-weight:600;color:#1a1a1a">${S.kloeTitle}</p>
          <p style="margin:4px 0 0;font-size:13px;color:#4b5563">Due: ${S.dueDate}</p>
        </td>
      </tr>
    </table>
    <p style="margin:0 0 24px">
      Please log in to the AlwaysReady platform and complete your review before the due date.
    </p>
    <p style="margin:0 0 24px">
      <a href="https://portal.alwaysready.uk/dashboard/kloes" style="display:inline-block;background:#014D4E;color:#ffffff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px">
        Go to KLOE tracker →
      </a>
    </p>
    <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
      If you've already completed this review, you can ignore this message.
    </p>
  `,
  })

  entries.push({
    id: 'kloe_review_overdue',
    label: 'KLOE review overdue',
    group: 'Platform',
    params: ['kloeTitle', 'dueDate'],
    sampleParams: { kloeTitle: S.kloeTitle, dueDate: S.dueDate },
    sampleHtml: `
    <p style="margin:0 0 16px">
      A KLOE review assigned to you is now <strong style="color:#dc2626">overdue</strong>.
    </p>
    <table style="width:100%;border-collapse:collapse;margin:0 0 24px">
      <tr>
        <td style="padding:12px 16px;background:#fef2f2;border:1px solid #fecaca;border-radius:8px">
          <p style="margin:0 0 4px;font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">KLOE</p>
          <p style="margin:0;font-weight:600;color:#1a1a1a">${S.kloeTitle}</p>
          <p style="margin:4px 0 0;font-size:13px;color:#dc2626">Was due: ${S.dueDate}</p>
        </td>
      </tr>
    </table>
    <p style="margin:0 0 24px">
      Please log in and complete this review as soon as possible to keep your compliance record up to date.
    </p>
    <p style="margin:0 0 24px">
      <a href="https://portal.alwaysready.uk/dashboard/kloes" style="display:inline-block;background:#014D4E;color:#ffffff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px">
        Go to KLOE tracker →
      </a>
    </p>
    <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
      If you have any questions, reply to this email or contact us at
      <a href="mailto:support@alwaysready.uk" style="color:#014D4E">support@alwaysready.uk</a>.
    </p>
  `,
  })

  entries.push({
    id: 'hr_field_due_soon',
    label: 'HR record due soon',
    group: 'Platform',
    params: ['staffName', 'fieldLabel', 'dueDate', 'daysLeft'],
    sampleParams: { staffName: S.staffName, fieldLabel: S.fieldLabel, dueDate: S.dueDate, daysLeft: S.daysLeft },
    sampleHtml: `
    <p style="margin:0 0 16px">
      <strong>${S.staffName}</strong>'s <strong>${S.fieldLabel}</strong> is due in <strong>${S.daysLeft} days</strong>.
    </p>
    <table style="width:100%;border-collapse:collapse;margin:0 0 24px">
      <tr>
        <td style="padding:12px 16px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px">
          <p style="margin:0 0 4px;font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Staff member</p>
          <p style="margin:0;font-weight:600;color:#1a1a1a">${S.staffName}</p>
          <p style="margin:4px 0 0;font-size:13px;color:#4b5563">${S.fieldLabel}: due ${S.dueDate}</p>
        </td>
      </tr>
    </table>
    <p style="margin:0 0 24px">
      Please log in to the AlwaysReady HR module to review and update this record.
    </p>
    <p style="margin:0 0 24px">
      <a href="https://portal.alwaysready.uk/dashboard/hr" style="display:inline-block;background:#014D4E;color:#ffffff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px">
        Go to HR module →
      </a>
    </p>
  `,
  })

  entries.push({
    id: 'hr_field_overdue',
    label: 'HR record overdue',
    group: 'Platform',
    params: ['staffName', 'fieldLabel', 'dueDate'],
    sampleParams: { staffName: S.staffName, fieldLabel: S.fieldLabel, dueDate: S.dueDate },
    sampleHtml: `
    <p style="margin:0 0 16px">
      <strong>${S.staffName}</strong>'s <strong>${S.fieldLabel}</strong> is now <strong style="color:#dc2626">overdue</strong>.
    </p>
    <table style="width:100%;border-collapse:collapse;margin:0 0 24px">
      <tr>
        <td style="padding:12px 16px;background:#fef2f2;border:1px solid #fecaca;border-radius:8px">
          <p style="margin:0 0 4px;font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Staff member</p>
          <p style="margin:0;font-weight:600;color:#1a1a1a">${S.staffName}</p>
          <p style="margin:4px 0 0;font-size:13px;color:#dc2626">${S.fieldLabel}: was due ${S.dueDate}</p>
        </td>
      </tr>
    </table>
    <p style="margin:0 0 24px">
      <a href="https://portal.alwaysready.uk/dashboard/hr" style="display:inline-block;background:#014D4E;color:#ffffff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px">
        Go to HR module →
      </a>
    </p>
  `,
  })

  entries.push({
    id: 'support_ticket_received',
    label: 'Support ticket received (customer acknowledgement)',
    group: 'Support',
    params: ['firstName', 'reference', 'subject'],
    sampleParams: { firstName: S.firstName, reference: S.reference, subject: S.subject },
    sampleHtml: `
      <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#1a1a1a">
        Thank you for getting in touch, ${S.firstName}. We've received your support request and will get back to you as soon as possible.
      </p>

      <div style="margin:0 0 24px;padding:16px 20px;background:#f5f4f1;border-left:4px solid #014D4E;border-radius:4px">
        <p style="margin:0 0 6px;font-size:12px;font-weight:600;color:#555;text-transform:uppercase;letter-spacing:0.05em">Your request</p>
        <p style="margin:0 0 4px;font-size:13px;color:#888;font-family:monospace">${S.reference}</p>
        <p style="margin:0;font-size:15px;font-weight:600;color:#1a1a1a">${S.subject}</p>
      </div>

      <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
        You can reply to this email directly, or visit the <strong>Support</strong> section
        inside AlwaysReady to view your request and any replies.
      </p>
    `,
  })

  entries.push({
    id: 'support_ticket_reply',
    label: 'Support ticket staff reply (website enquiry)',
    group: 'Support',
    params: ['firstName', 'message'],
    sampleParams: { firstName: S.firstName, message: S.message },
    sampleHtml: `
        <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#1a1a1a">
          Thank you for getting in touch, ${S.firstName}. Here is our response to your enquiry:
        </p>

        <div style="margin:0 0 24px;padding:16px 20px;background:#f5f4f1;border-left:4px solid #014D4E;border-radius:4px;font-size:15px;line-height:1.7;color:#1a1a1a;white-space:pre-wrap">${S.message}</div>

        <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
          If you have any further questions, please reply to this email or visit
          <a href="https://www.alwaysready.uk" style="color:#014D4E">www.alwaysready.uk</a>.
        </p>
      `,
  })

  entries.push({
    id: 'support_ticket_resolved',
    label: 'Support ticket resolved',
    group: 'Support',
    params: ['firstName', 'reference', 'subject', 'followUpText'],
    sampleParams: { firstName: S.firstName, reference: S.reference, subject: S.subject, followUpText: S.followUpText },
    sampleHtml: `
            <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#1a1a1a">
              Your support request has been resolved, ${S.firstName}.
            </p>

            <div style="margin:0 0 24px;padding:16px 20px;background:#f5f4f1;border-left:4px solid #014D4E;border-radius:4px">
              <p style="margin:0 0 6px;font-size:12px;font-weight:600;color:#555;text-transform:uppercase;letter-spacing:0.05em">Resolved request</p>
              <p style="margin:0 0 4px;font-size:13px;color:#888;font-family:monospace">${S.reference}</p>
              <p style="margin:0;font-size:15px;font-weight:600;color:#1a1a1a">${S.subject}</p>
            </div>

            <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#1a1a1a">
              ${S.followUpText}
            </p>

            <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
              Thank you for using AlwaysReady. We hope we were able to help.
            </p>
          `,
  })

  entries.push({
    id: 'provision_welcome',
    label: 'New org welcome (login details)',
    group: 'Account',
    params: ['adminName', 'orgName', 'loginUrl', 'adminEmail', 'adminPassword', 'trialExpiry', 'charityNote'],
    sampleParams: {
      adminName: S.adminName, orgName: S.orgName, loginUrl: S.loginUrl, adminEmail: S.adminEmail,
      adminPassword: S.adminPassword, trialExpiry: S.trialExpiry, charityNote: S.charityNote,
    },
    sampleHtml: `
        <p style="margin:0 0 16px">
          Welcome to AlwaysReady, ${S.adminName}. Your account for
          <strong>${S.orgName}</strong> is ready. You can log in right now.
        </p>

        <table role="presentation" cellspacing="0" cellpadding="0" border="0"
          style="background:#f5f5f0;border-radius:6px;padding:20px 24px;margin:0 0 24px;width:100%">
          <tr>
            <td style="font-size:14px;line-height:2">
              <strong>Login URL:</strong>
              <a href="${S.loginUrl}" style="color:#014D4E">${S.loginUrl}</a><br>
              <strong>Email:</strong> ${S.adminEmail}<br>
              <strong>Password:</strong> ${S.adminPassword}<br>
              <strong>Trial expires:</strong> ${S.trialExpiry}
            </td>
          </tr>
        </table>

        <p style="margin:0 0 16px;background:#fef9ec;border-left:4px solid #ffd700;padding:12px 16px;border-radius:4px;font-size:15px;color:#1a1a1a;line-height:1.7">
          <strong>A note on security</strong><br>
          AlwaysReady holds your service's compliance records, evidence documents, and staff data.
          This is sensitive information, and we take the security of your account seriously.<br><br>
          Before you do anything else, please complete these two steps:<br><br>
          1. <strong>Change your password</strong>: replace the temporary password above with one
          that is unique to you. Go to <strong>Account → Security → Change password</strong>.<br>
          2. <strong>Set up two-factor authentication (MFA)</strong>: the platform will prompt you
          to do this automatically when you first log in. MFA means that even if your password were
          ever compromised, your account cannot be accessed without a second verification step on
          your phone or authenticator app.
        </p>

        ${S.charityNote}
        <p style="margin:0 0 16px">
          As the account admin, you can add your team, assign KLOEs, and start
          building your inspection readiness from day one. If you have any
          questions, just reply to this email or open a support ticket from
          within the platform.
        </p>

        <p style="margin:0 0 24px">
          <a href="${S.loginUrl}"
            style="display:inline-block;background:#ffd700;color:#014D4E;font-weight:700;
                   font-size:14px;padding:12px 28px;border-radius:8px;text-decoration:none">
            Log in to AlwaysReady →
          </a>
        </p>

        <p style="margin:0;color:#555">
          AJ Parker<br>
          <span style="color:#888;font-size:13px">AlwaysReady · support@alwaysready.uk</span>
        </p>
      `,
  })

  entries.push({
    id: 'data_deletion_reminder',
    label: 'Data deletion warning (3 days)',
    group: 'Account',
    params: ['firstName', 'orgName', 'deletionDate'],
    sampleParams: { firstName: S.firstName, orgName: S.orgName, deletionDate: S.deletionDate },
    sampleHtml: `
          <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
            This is a reminder, ${S.firstName}, that the data for <strong>${S.orgName}</strong> on AlwaysReady
            will be permanently deleted on <strong>${S.deletionDate}</strong>, in 3 days.
          </p>
          <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
            You can download your data now by logging in and using the download buttons
            on the page shown. You can also resubscribe at any time before that date to
            keep your account and all your data.
          </p>
          <p style="margin:0 0 32px">
            <a href="https://portal.alwaysready.uk/login"
               style="display:inline-block;background-color:#014D4E;color:#ffffff;padding:14px 28px;border-radius:6px;font-size:15px;font-weight:600;text-decoration:none">
              Log in to download or resubscribe &rarr;
            </a>
          </p>
          <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
            If you have any questions, email us at
            <a href="mailto:support@alwaysready.uk" style="color:#014D4E">support@alwaysready.uk</a>.
          </p>
        `,
  })

  entries.push({
    id: 'data_deletion_completed',
    label: 'Data deletion completed',
    group: 'Account',
    params: ['firstName', 'orgName'],
    sampleParams: { firstName: S.firstName, orgName: S.orgName },
    sampleHtml: `
          <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
            As notified, ${S.firstName}, all data associated with <strong>${S.orgName}</strong> on AlwaysReady
            has now been permanently deleted in accordance with our data retention policy. It has been removed from our live systems, and any encrypted backup copies are automatically deleted within 30 days.
          </p>
          <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
            One exception: our payment processor, Stripe, is legally required to retain certain billing and
            transaction records for a period after your subscription ends, as required under UK tax and
            financial record-keeping law. Stripe holds this independently of AlwaysReady; we do not have
            access to it once your account is deleted, and it is not used for anything beyond Stripe's own
            legal obligations.
          </p>
          <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
            If you'd like to start a new account in the future, you're very welcome to do so.
          </p>
          <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
            If you have any questions about this deletion, please contact
            <a href="mailto:support@alwaysready.uk" style="color:#014D4E">support@alwaysready.uk</a>.
          </p>
        `,
  })

  entries.push({
    id: 'blog_subscriber_deletion_completed',
    label: 'Blog subscriber data deletion completed (self-service)',
    group: 'Website',
    params: ['firstName'],
    sampleParams: { firstName: S.firstName },
    sampleHtml: `
      <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
        Your AlwaysReady blog subscriber data has been permanently deleted, ${S.firstName}, in accordance
        with your request.
      </p>
      <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
        This includes your email address, name, and subscription record. It has been removed from our live systems, and any encrypted backup copies are automatically deleted within 30 days.
        You will not receive any further emails from us unless you subscribe again in future.
      </p>
      <p style="margin:0 0 24px;font-size:15px;line-height:1.7;color:#1a1a1a">
        If you would like to subscribe again at any point, you are very welcome to do so
        at <a href="https://alwaysready.uk/blog" style="color:#014D4E">alwaysready.uk/blog</a>.
      </p>
      <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
        If you have any questions about this deletion, contact us at
        <a href="mailto:support@alwaysready.uk" style="color:#014D4E">support@alwaysready.uk</a>.
      </p>
    `,
  })

  entries.push({
    id: 'notification_reconfirmation',
    label: 'Notification re-confirmation check-in',
    group: 'Account',
    params: ['notificationsList'],
    sampleParams: { notificationsList: S.notificationsList },
    sampleHtml: `
    <p style="margin:0 0 16px">
      You're currently receiving these AlwaysReady email notifications:
    </p>
    <ul style="margin:0 0 24px;padding-left:20px">
      ${S.notificationsList}
    </ul>
    <p style="margin:0 0 24px">
      Still want these? You can turn any of them off, or back on, from your account settings.
    </p>
    <p style="margin:0 0 24px">
      <a href="https://portal.alwaysready.uk/dashboard/account?tab=notifications" style="display:inline-block;background:#014D4E;color:#ffffff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px">
        Manage notification preferences →
      </a>
    </p>
    <p style="margin:0;font-size:15px;line-height:1.7;color:#1a1a1a">
      While you're there, we'd appreciate a quick word on how useful they've been. There's a short optional
      feedback box on the same page.
    </p>
  `,
  })

  entries.push({
    id: 'governance_digest',
    label: 'Weekly governance digest (report shell)',
    group: 'Account',
    params: ['orgName', 'readinessPct', 'reportDate'],
    sampleParams: { orgName: S.orgName, readinessPct: S.readinessPct, reportDate: S.reportDate },
    sampleHtml: `
      <p style="margin:0 0 8px;font-size:13px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Weekly governance digest &middot; ${S.reportDate}</p>
      <h2 style="margin:0 0 16px;font-size:20px;color:#1a1a1a">${S.orgName}: ${S.readinessPct}% ready</h2>
      <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#1a1a1a">
        This is a generated weekly report. Its figures (readiness percentage, overdue items, open
        incidents) are computed fresh on every send from live data, so editing this template changes
        the wording and layout around those figures, not the figures themselves.
      </p>
      <p style="margin:0 0 24px">
        <a href="https://portal.alwaysready.uk/dashboard/daily-report" style="display:inline-block;background:#014D4E;color:#ffffff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px">
          View full report →
        </a>
      </p>
    `,
  })

  return entries
}

export function getRegisteredTemplate(id: string): RegisteredTemplate | undefined {
  return getRegistry().find(t => t.id === id)
}
