/**
 * POST /api/report-narrative
 *
 * Accepts a summary of the current report state and returns a plain English
 * board-ready paragraph generated by Claude Haiku.
 *
 * Admin only.
 */
import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { getCurrentUserProfile } from '@/lib/session'
import { createRateLimiter } from '@/lib/rate-limit'

// 20 AI calls per org per hour — enough for normal use, prevents runaway spend.
const narrativeLimiter = createRateLimiter({ windowMs: 60 * 60_000, max: 20 })

interface ReportSnapshot {
  orgName: string
  generatedAt: string
  kloes: {
    total: number
    green: number
    amber: number
    red: number
    unassessed: number
    items: { title: string; keyQuestion: string; rag: string; status: string }[]
  }
  actions: {
    total: number
    open: number
    overdue: number
    items: { title: string; status: string; dueDate: string | null; priority: string }[]
  }
  viewLabel: string | null
}

const client = new Anthropic()

export async function POST(req: NextRequest) {
  const profile = await getCurrentUserProfile()
  if (profile?.role !== 'admin') {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  // Rate limit by org — prevents a single org burning the Anthropic API budget.
  if (!(await narrativeLimiter.check(`report-narrative:${profile.organisation_id}`))) {
    return NextResponse.json(
      { error: 'Too many requests. Please wait before generating another summary.' },
      { status: 429 }
    )
  }

  let body: ReportSnapshot
  try {
    body = await req.json() as ReportSnapshot
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 })
  }

  const { orgName, generatedAt, kloes, actions, viewLabel } = body

  const prompt = `You are writing a governance summary paragraph for a care home's compliance report.

Organisation: ${orgName}
Report date: ${generatedAt}
Report type: ${viewLabel ?? 'Custom Report'}

KLOE compliance status:
- Total KLOEs in this report: ${kloes.total}
- Green (compliant): ${kloes.green}
- Amber (needs attention): ${kloes.amber}
- Red (non-compliant): ${kloes.red}
- Unassessed: ${kloes.unassessed}

${kloes.amber > 0 || kloes.red > 0 || kloes.unassessed > 0 ? `KLOEs requiring attention:
${kloes.items
  .filter(k => k.rag !== 'green')
  .slice(0, 8)
  .map(k => `- ${k.title} (${k.keyQuestion}): ${k.rag === 'grey' ? 'Unassessed' : k.rag.charAt(0).toUpperCase() + k.rag.slice(1)}`)
  .join('\n')}` : ''}

Action plan:
- Total actions: ${actions.total}
- Open actions: ${actions.open}
- Overdue actions: ${actions.overdue}

Write a single concise paragraph (3–5 sentences) summarising the compliance position for a board or management meeting. Use plain English — no jargon, no bullet points, no headers. Be factual and specific. Acknowledge both strengths and areas for improvement. Do not start with "As of" — vary the opening. Do not use the word "significant" or "proactive". Do not pad the paragraph.`

  try {
    const message = await client.messages.create({
      model:      'claude-haiku-4-5-20251001',
      max_tokens: 300,
      messages:   [{ role: 'user', content: prompt }],
    })

    const text = message.content
      .filter(b => b.type === 'text')
      .map(b => (b as { type: 'text'; text: string }).text)
      .join('')

    return NextResponse.json({ narrative: text.trim() })
  } catch (err) {
    console.error('[report-narrative] AI error:', err)
    return NextResponse.json({ error: 'Failed to generate summary' }, { status: 500 })
  }
}
