/**
 * The CRON_SECRET the e2e dev server was started with for the /api/cron/*
 * routes. playwright.config.ts generates a fresh random value for every test
 * run, passes it to the webServer, and exposes it to the worker processes as
 * E2E_CRON_SECRET, which is read back here. It is deliberately not a literal:
 * the repository is public, so nothing that looks like a credential belongs in it.
 */
const secret = process.env.E2E_CRON_SECRET

if (!secret) {
  throw new Error(
    'E2E_CRON_SECRET is not set. It is generated by playwright.config.ts, so run these specs ' +
      'through `npm run test:e2e` (or `npx playwright test`) rather than importing this file directly.',
  )
}

export const CRON_SECRET: string = secret
