'use client'

import { useState, useTransition } from 'react'
import { generateNewsletter } from '@/app/actions/newsletter'

const AUDIENCES = [
  'Staff team',
  'Families and residents',
  'Staff team and families',
]

const OCCASIONS = [
  'Monthly update',
  'Upcoming CQC inspection',
  'Policy or procedure change',
  'Seasonal / holiday message',
  'Staff recognition',
  'CQC rating update',
  'New staff members',
  'Service changes',
  'Other (I\'ll describe in key points)',
]

const TONES = ['Warm and friendly', 'Professional', 'Brief and factual']

type Props = {
  initialRemaining: number
}

export default function NewsletterForm({ initialRemaining }: Props) {
  const [audience, setAudience]   = useState(AUDIENCES[0])
  const [occasion, setOccasion]   = useState(OCCASIONS[0])
  const [keyPoints, setKeyPoints] = useState('')
  const [tone, setTone]           = useState(TONES[0])
  const [draft, setDraft]         = useState('')
  const [remaining, setRemaining] = useState(initialRemaining)
  const [error, setError]         = useState('')
  const [copied, setCopied]       = useState(false)
  const [isPending, startTransition] = useTransition()

  function handleGenerate() {
    setError('')
    setCopied(false)
    startTransition(async () => {
      const result = await generateNewsletter({ audience, occasion, keyPoints, tone })
      if (result.success) {
        setDraft(result.draft)
        setRemaining(result.remaining)
      } else {
        setError(result.error)
      }
    })
  }

  function handleCopy() {
    navigator.clipboard.writeText(draft).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  const atLimit = remaining <= 0

  return (
    <div className="space-y-6">

      {/* ── Notice — full width above both columns ───────────────────────── */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
        <p className="text-sm font-semibold text-amber-900 mb-1.5">Before you start</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-x-6 gap-y-1">
          <p className="text-sm text-amber-800">🤖 Drafts are generated by AI. Always read and edit before use.</p>
          <p className="text-sm text-amber-800">🔒 No resident, patient, or family names or personal details.</p>
          <p className="text-sm text-amber-800">🔒 No individual staff details (full name combined with role, health or HR information).</p>
          <p className="text-sm text-amber-800">📋 For copying and pasting only. AlwaysReady does not store or send it.</p>
        </div>
      </div>

      {/* ── Two-column layout ────────────────────────────────────────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-[380px_1fr] gap-6 items-start">

      {/* ── Left: controls ──────────────────────────────────────────────── */}
      <div className="space-y-5">

        {/* Usage pill */}
        <div>
          <span className={`inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-full ${
            atLimit
              ? 'bg-red-50 text-red-700'
              : remaining <= 3
              ? 'bg-amber-50 text-amber-700'
              : 'bg-[#014D4E]/10 text-brand'
          }`}>
            {atLimit
              ? 'Monthly limit reached — resets on the 1st'
              : `${remaining} draft${remaining === 1 ? '' : 's'} remaining this month`}
          </span>
        </div>

        {/* Form card */}
        <div className="bg-card border border-line rounded-xl p-5 space-y-5">

          {/* Audience */}
          <div>
            <label htmlFor="audience" className="block text-sm font-medium text-ink mb-1.5">
              Who is this for?
            </label>
            <select
              id="audience"
              value={audience}
              onChange={e => setAudience(e.target.value)}
              className="w-full text-sm border border-line rounded-lg px-3 py-2 bg-card focus:outline-none focus:ring-2 focus:ring-[#014D4E]"
            >
              {AUDIENCES.map(a => <option key={a}>{a}</option>)}
            </select>
          </div>

          {/* Occasion */}
          <div>
            <label htmlFor="occasion" className="block text-sm font-medium text-ink mb-1.5">
              Topic or occasion
            </label>
            <select
              id="occasion"
              value={occasion}
              onChange={e => setOccasion(e.target.value)}
              className="w-full text-sm border border-line rounded-lg px-3 py-2 bg-card focus:outline-none focus:ring-2 focus:ring-[#014D4E]"
            >
              {OCCASIONS.map(o => <option key={o}>{o}</option>)}
            </select>
          </div>

          {/* Key points */}
          <div>
            <label htmlFor="keypoints" className="block text-sm font-medium text-ink mb-1.5">
              Key points to include{' '}
              <span className="text-ink-muted font-normal">(optional)</span>
            </label>
            <textarea
              id="keypoints"
              rows={4}
              value={keyPoints}
              onChange={e => setKeyPoints(e.target.value)}
              placeholder="e.g. New visiting hours from 1 August, welcome to two new staff members, summer BBQ on 15 August"
              className="w-full text-sm border border-line rounded-lg px-3 py-2 resize-none focus:outline-none focus:ring-2 focus:ring-[#014D4E]"
            />
          </div>

          {/* Tone */}
          <div>
            <p className="text-sm font-medium text-ink mb-2">Tone</p>
            <div className="flex flex-wrap gap-2">
              {TONES.map(t => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setTone(t)}
                  className={`text-sm px-4 py-1.5 rounded-full border transition-colors focus:outline-none focus:ring-2 focus:ring-[#014D4E] ${
                    tone === t
                      ? 'bg-[#014D4E] text-white border-[#014D4E]'
                      : 'bg-card text-ink-dim border-line hover:border-[#014D4E]'
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>

          {/* Error */}
          {error && (
            <div className="text-sm text-red-700 bg-red-50 border border-red-200 rounded-lg px-4 py-3">
              {error}
            </div>
          )}

          {/* Generate button */}
          <button
            type="button"
            onClick={handleGenerate}
            disabled={isPending || atLimit}
            className="w-full py-3 bg-[#014D4E] text-white text-sm font-semibold rounded-lg hover:bg-[#00b8a6] hover:text-brand transition-colors disabled:opacity-50 disabled:cursor-not-allowed focus:outline-none focus:ring-2 focus:ring-[#014D4E] focus:ring-offset-2"
          >
            {isPending ? 'Generating draft…' : draft ? 'Regenerate draft' : 'Generate draft'}
          </button>
        </div>
      </div>

      {/* ── Right: draft output ─────────────────────────────────────────── */}
      <div className="bg-card border border-line rounded-xl overflow-hidden flex flex-col" style={{ minHeight: '560px' }}>

        {/* Panel header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-line">
          <p className="text-xs font-semibold text-ink-muted uppercase tracking-widest">
            Your draft
          </p>
          {draft && (
            <span className="inline-flex items-center gap-1 text-xs font-medium text-brand bg-[#014D4E]/10 px-2.5 py-1 rounded-full">
              AI generated
            </span>
          )}
        </div>

        {/* Draft area */}
        {draft ? (
          <div className="flex flex-col flex-1 p-5 gap-4">
            <textarea
              value={draft}
              onChange={e => setDraft(e.target.value)}
              className="flex-1 w-full text-sm text-ink leading-relaxed bg-canvas rounded-lg p-4 border border-line resize-none focus:outline-none focus:ring-2 focus:ring-[#014D4E]"
              style={{ minHeight: '440px' }}
              aria-label="Generated newsletter draft — editable"
            />
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={handleCopy}
                className="flex items-center gap-2 text-sm font-medium text-brand border border-line rounded-lg px-4 py-2 hover:border-[#014D4E] transition-colors focus:outline-none focus:ring-2 focus:ring-[#014D4E]"
              >
                {copied ? '✓ Copied' : 'Copy text'}
              </button>
              <p className="text-sm text-ink-muted">
                Review and edit before sending.
              </p>
            </div>
          </div>
        ) : (
          <div className="flex-1 flex flex-col items-center justify-center text-center p-8 gap-3">
            {isPending ? (
              <>
                <div className="w-8 h-8 border-2 border-[#014D4E] border-t-transparent rounded-full animate-spin" aria-hidden="true" />
                <p className="text-sm text-ink-muted">Generating your draft…</p>
              </>
            ) : (
              <>
                <div className="w-12 h-12 rounded-full bg-[#014D4E]/10 flex items-center justify-center mb-1">
                  <svg className="w-6 h-6 text-brand" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5} aria-hidden="true">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                  </svg>
                </div>
                <p className="text-sm font-medium text-ink">Your draft will appear here</p>
                <p className="text-sm text-ink-muted max-w-xs">
                  Choose your audience, topic, and tone on the left, then click <strong>Generate draft</strong>.
                </p>
              </>
            )}
          </div>
        )}
        </div>

      </div>{/* end two-column grid */}
    </div>
  )
}
