/**
 * /dashboard/newsletter — AI newsletter drafting tool.
 * Admin only. Generates draft newsletters for staff, families, or both.
 * Limited to 10 AI generations per organisation per calendar month.
 */
import { redirect } from 'next/navigation'
import Link from 'next/link'
import { getCurrentUserProfile } from '@/lib/session'
import { getNewsletterUsage } from '@/app/actions/newsletter'
import NewsletterForm from './NewsletterForm'

export const metadata = { title: 'Newsletter drafting — AlwaysReady' }

export default async function NewsletterPage() {
  const profile = await getCurrentUserProfile()

  if (!profile) redirect('/login')
  if (profile.role !== 'admin') redirect('/dashboard')

  const { remaining } = await getNewsletterUsage()

  return (
    <div className="max-w-2xl mx-auto">
      {/* Breadcrumb */}
      <nav className="text-sm text-ink-muted mb-2" aria-label="Breadcrumb">
        <ol className="flex flex-wrap gap-1">
          <li><Link href="/dashboard" className="hover:text-brand underline">Dashboard</Link></li>
          <li aria-hidden="true">/</li>
          <li className="text-ink" aria-current="page">Newsletter drafting</li>
        </ol>
      </nav>

      <div className="mb-6">
        <h1 className="text-2xl font-bold text-brand mb-2">Newsletter drafting</h1>
        <p className="text-sm text-ink-dim leading-relaxed">
          Generate a draft newsletter for your staff or families. Copy the finished text and send it
          however you like — email, print, or message. AlwaysReady doesn&apos;t send on your behalf.
        </p>
      </div>

      {/* AI + data notice */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-8 space-y-1.5">
        <p className="text-sm font-semibold text-amber-900">Before you start</p>
        <ul className="text-sm text-amber-800 space-y-1 list-none">
          <li>🤖 Drafts are generated by AI. Always read and edit the output before you use it.</li>
          <li>🔒 Do not include personal details of residents, patients, or families in your key points — names, health information, and personal circumstances should never be entered into this tool.</li>
          <li>🔒 Do not include personal details of individual staff members (full name combined with role, health or HR information).</li>
          <li>📋 The finished draft is for copying and pasting into your preferred medium — email, printed letter, messaging app. AlwaysReady does not store or send it.</li>
        </ul>
      </div>

      <NewsletterForm initialRemaining={remaining} />
    </div>
  )
}
