-- ── Email archive ("View in Browser") ───────────────────────────────────────
--
-- Backs the new "View in Browser" footer link on every email sendEmail()
-- sends (lib/email.ts). The id IS the access token -- an unguessable v4 uuid
-- generated by the app before sending, embedded in that email's own
-- "View in Browser" link, then stored here alongside the exact HTML that
-- was actually sent. app/email/view/[id]/route.ts serves it back verbatim,
-- publicly and without login, the same way every major ESP's own
-- "view in browser" link works -- there is no session to require one of,
-- since the point is someone reading their inbox, not the platform.
--
-- This does mean the link is a bearer credential: whoever has the URL can
-- view that email's content (which can be personalised). That is the
-- accepted, industry-standard tradeoff for this feature, not an oversight --
-- same as an unsubscribe link already is in this codebase.
--
-- No RLS policies granted to `authenticated`: every write happens from
-- sendEmail() via the service-role admin client, and the public view route
-- also reads via the admin client (deliberately -- there is no end-user
-- session to check RLS against for a link clicked from an email client).

CREATE TABLE IF NOT EXISTS public.email_archive (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  subject    text        NOT NULL,
  body_html  text        NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.email_archive ENABLE ROW LEVEL SECURITY;
-- No policies: service-role only, by design (see comment above).
