-- Migration: Fix truncated rating characteristics in klo_items
-- Source: CQC_Draft_Assessment_Framework_ASC_v9.docx (authoritative)
-- 9 rating bands were truncated in 20260714000005_klo_items.sql
-- Generated: 20 July 2026

-- Evidence-based care and equitable outcomes / Good
UPDATE klo_items SET rating_good = $$People receive care, support and treatment aligned to recognised good practice standards. Staff and leaders understand the current legislation, standards and good practice relevant to their service and apply these effectively. They have good systems to ensure they keep up-to-date and embed this in their service. People understand how current ‘good practice’ is relevant to their outcomes, and they are involved in planning how this is reflected in their care, support and treatment. The service understands what people expect from their care and what good outcomes look like for them. These outcomes are regularly achieved. The service empowers people to understand their legal rights to equity of care and outcomes. Staff recognise barriers that prevent equity. Information is collected and acted on, and resources are allocated, to reduce these barriers and improve people’s outcomes. There is a rigorous approach to monitoring the effectiveness of people’s care, support and treatment and the service takes action to continuously improve it. Staff monitor and evaluate outcomes related to people’s health and quality of life, including those linked to their aspirations and skill development, and act to improve them when possible. People’s nutritional and hydration needs are met in line with current standards and good practice guidance. Where applicable, there is positive feedback from dietetic professionals that the service asks for their advice and applies it properly. People are supported to plan and manage their dietary needs and associated risks, including risks of poor nutrition, dehydration, swallowing problems and other medical conditions that affect their health. Staff are aware of individual preferences in relation to eating and drinking and there is flexibility when needed or requested. There are good quality food choices and these respect individual wishes, including those relating to sensory, cultural, religious and ethical preferences.$$
WHERE title = $$Evidence-based care and equitable outcomes$$;

-- Evidence-based care and equitable outcomes / Requires improvement
UPDATE klo_items SET rating_ri = $$The service doesn’t always recognise, understand or implement current relevant recognised good practice guidance, legislation and standards and it is not always reflected in people’s care, support and treatment. The service doesn’t routinely support people in understanding what good practice means for them and their outcomes. This can mean people have a limited understanding of the expected outcomes of their care. Not all people feel enabled to fully give their views or they feel that their rights are not respected in relation to their experience and outcomes of their care. This is particularly the case where people feel they are treated inequitably based on their protected equality characteristics. Staff and leaders do not have a good understanding of the people using their service who are most likely to experience discrimination and inequality in experience or outcomes. The service will miss opportunities or does not consistently take appropriate steps to promote and provide equitable experiences or outcomes for people. The service does not adequately monitor and evaluate the effectiveness of people’s care, support and treatment consistently. Opportunities to improve care can be missed, or people do not have the best possible outcomes from their care. People’s nutritional needs are not always met in line with relevant standards and good practice. People may not always get enough to eat or drink or be supported to get enough to eat and drink. People are not consistently supported to eat a healthy, balanced diet because options are limited, and not all the food provided is appropriate to meet people’s nutritional needs. The service does not routinely involve people in planning their meals and does not act on people’s feedback about their food. People’s cultural, ethical and religious needs in relation to food or drink are not well understood. The service does not sufficiently monitor or manage the risks associated with eating and drinking, including poor hydration and nutrition and swallowing difficulties. The service does not routinely request or enable access to dietary and nutritional specialists when needed.$$
WHERE title = $$Evidence-based care and equitable outcomes$$;

-- Person-centred care / Outstanding
UPDATE klo_items SET rating_outstanding = $$People are helped and supported to genuinely express their wishes and preferences. People at this service can authentically be themselves and live the life they choose. The service embodies a ‘how to make this happen for people’ approach. Care goes beyond meeting clinical or personal care needs, to supporting and empowering people to achieve what is important to them. The service recognises the limitations of the settings where care is delivered, particularly where people’s needs may conflict with other people’s wishes and staff are particularly skilled when exploring and resolving any conflicts and tensions involved. The service understands that a person’s needs, preferences and wishes can change, and it makes sure it continuously adapts its approach with the person for meaningful outcomes. There are creative ways of reflecting people’s personal histories and cultural backgrounds, and the service strives to match staff with people’s interests and personalities.$$
WHERE title = $$Person-centred care$$;

-- Independence, choice and control / Requires improvement
UPDATE klo_items SET rating_ri = $$The service does not appropriately support or enable people to have as much choice and control over their care as possible. People cannot meaningfully engage in decisions about their care, support and treatment and the outcomes they want to achieve. People’s social needs are not fully understood, and they are not supported to meet these needs. People at times face unreasonable or avoidable barriers or restrictions on access to their family, friends and community. When applicable, relatives and friends are not always welcome when visiting the service or are unclear about the reasons for any restrictions. The service does not appropriately consider people’s right to privacy and right to have a personal life, including intimate relationships, and how it supports them. The service does not consistently support people to follow their interests, access meaningful activities or hobbies, or they are not encouraged to take part in social activities or maintain personal or community relationships. Appropriate equipment and/or technology is not routinely available to support people’s independence. Where applicable, people are not well supported to make choices or retain control over how spaces are arranged and used. People are not engaged and supported in planning for the future where it is appropriate and expected that the service would do this. This includes planning for important life changes and future care needs. People’s decisions about their future care needs are not appropriately re-assessed and reviewed with them. Their wishes are not consistently recorded or acted on. People are not consistently supported to make decisions about end of life care and advance decisions when they wish to. Some staff do not appreciate the need for good end of life care, and they do not consistently respond soon enough or involve the correct healthcare professionals. Support, equipment and medicines are not consistently provided in a timely way. People’s diverse preferences (including those arising from protected equality characteristics) are not always considered or acted on, or choices are not respected. The service does not consistently adopt a compassionate and supportive approach towards those close to the person, or staff, before and after a person dies.$$
WHERE title = $$Independence, choice and control$$;

-- Independence, choice and control / Inadequate
UPDATE klo_items SET rating_inadequate = $$People do not have meaningful choice and control about their care, support, treatment and wellbeing. People’s social needs are not adequately considered or met. The service unreasonably restricts people’s access to their family, friends and community. When applicable, visiting restrictions have been put in place without communicating with those using the service or those close to them who are affected. If people have raised concerns about the service, they have been asked to leave. Friends and family have been prevented from visiting if they have raised concerns. People are not listened to, and they are not supported to express their views or pursue their interests. Staff do not use accessible ways to communicate or make sure that people have understood them. The service does not consider or respect people’s right to privacy and a personal life, including intimate relationships. People are inappropriately discouraged or restricted in this area of their life. The service does not meet people’s individual needs in relation to maintaining interests and hobbies, maintaining relationships or contact with the local community. Appropriate adaptive or specialised equipment is not available to give people independence in the service where required. Where applicable, people are not supported to make choices or influence how spaces are arranged or used. The service fails to support people to plan for the future. This includes understanding and considering people’s views on their future care needs and life events. People’s wishes and decisions about their future care needs are not adequately recorded or are not acted on. People are not supported to make decisions about end of life care and advance decisions when they wish to. The service does not involve healthcare professionals, in response to people’s individual end of life needs and preferences. There is no consideration of diverse needs for end of life care, including religious beliefs and individual preferences, or these are not respected. There is a generic approach for all people, which doesn’t reflect their choices. The service does not adopt a compassionate and supportive approach towards those close to the person, or staff, before and after a person dies.$$
WHERE title = $$Independence, choice and control$$;

-- Equity in experiences / Requires improvement
UPDATE klo_items SET rating_ri = $$People do not consistently feel that the concerns they have raised about discrimination and inequality have been listened to, adequately understood or appropriately addressed. Staff and leaders do not have a good understanding of the impact on people who face or experience inequality. They do not understand how their approach to delivering care can either minimise or prevent this or add to this inequality. Staff lack confidence in understanding people’s equality-related needs and do not always understand how to meet them. Staff are not routinely equipped or supported to challenge inequality and discrimination or work with people to find solutions that work for them. There have been instances where the service had not complied with legal, equality and human rights requirements, including avoiding discrimination, having regard to the needs of people with different protected equality characteristics and making reasonable adjustments to support equity in experience and outcomes for relevant groups of people. The service does not routinely identify or meet people’s information and communication needs. For people who don’t speak English as a first language or who use British Sign language, information is not consistently presented or available in their preferred language. When applicable, the requirements of the Accessible Information Standard are not consistently met. People who have difficulty reading, writing or using digital services are not adequately supported to access information. The information and communication needs of people with a disability, impairment or sensory loss are not routinely met. Staff are not adequately supported to develop the skills they need to remove barriers to effective communication with all the people they support.$$
WHERE title = $$Equity in experiences$$;

-- Workforce equity and culture / Requires improvement
UPDATE klo_items SET rating_ri = $$Staff wellbeing, equality and inclusion are not routinely considered or supported and are not consistently demonstrated in the service’s culture. Communication with staff is unclear or lacks openness. Leaders do not consistently review their performance against equality, diversity and inclusion objectives. Staff are not equally valued, listened to or respected. The service does not consistently identify and reduce discrimination and unconscious bias. The service does not consistently promote equality, and diversity and inclusion. Not all staff have equitable access to personalised support that meets their diverse workplace needs. There is a lack of equitable access to opportunities, including fair access to personal and professional development, promotion, pay progression and leadership opportunities. Workforce inequalities are not consistently identified or addressed. Leaders do not monitor, evaluate and improve the culture of the service in the context of equality, diversity and inclusion. Leaders lack a proactive approach to effectively engaging and involving staff. In particular, they do not ensure they listen to the voices of staff who may experience discrimination based on their protected equality characteristics and those who are excluded or marginalised, or who may be least heard within their service. Arrangements for staff to raise concerns or contribute ideas are not effective. This includes weaknesses in how the process is communicated and how accessible it is to staff. Staff have concerns about being treated negatively and with a lack of compassion and understanding if they raise concerns. Investigations into issues are not conducted thoroughly in all cases, and those involved are not informed of the outcomes in a timely way. Action to prevent and address bullying and harassment across all levels is not consistently taken. Protecting people in relation to their protected equality characteristics and people from groups whose voices are seldom heard from bullying, harassment and victimisation often falls short.$$
WHERE title = $$Workforce equity and culture$$;

-- Workforce equity and culture / Inadequate
UPDATE klo_items SET rating_inadequate = $$Staff wellbeing, equality and inclusion are not considered. Leaders of the service do not understand the importance of transparent communication with staff and do not adopt an equality, diversity and human rights approach. Leaders do not set objectives or review their performance in relation to equality, diversity and inclusion. The needs of staff are frequently overlooked because diversity is not understood and acknowledged, or different needs are disregarded. There have been cases of workforce bullying, harassment, discrimination or violence, and the service does not take appropriate action to address these issues and/or prevent reoccurrence. Processes for staff to share feedback, raise concerns or contribute ideas are unclear or inaccessible. People and staff who raise concerns, including whistleblowers, are not supported and may be victimised. The issues they raise are not taken seriously or investigated. Psychological safety of staff is not prioritised. Leaders create an environment where staff feel they cannot make decisions or speak up for fear of victimisation, and do not feel supported to learn from mistakes. Staff face negative consequences as a result of raising concerns. Staff satisfaction levels are low, and staff report high levels of stress and work overload. Staff are not equally valued, listened to and respected. The service does not consistently identify and avoid discrimination and unconscious bias. It does not consistently promote equality, diversity and inclusion. Not all staff have equitable access to personalised support that meets their workplace needs, including equitable access to personal and professional development, promotion, pay progression and leadership opportunities. The service does not always consider reasonable adjustments for disabled staff to support them in their roles, or any adjustments are not adequate There is a poor service culture which results in staff and volunteers being treated without compassion or understanding. Discrimination or inequity are present.$$
WHERE title = $$Workforce equity and culture$$;

-- Governance and management / Requires improvement
UPDATE klo_items SET rating_ri = $$Governance and accountability arrangements are not consistently reliable, effective or regularly reviewed. Processes may be excessive or inaccessible and may inappropriately reduce autonomy of staff. Not all staff understand their roles and responsibilities. Required data and notification submissions are sometimes missed. There are shortfalls in record keeping and data management. Records may be incomplete, inaccurate or out-of-date. Records are not stored appropriately and securely. Not all staff understand data protection requirements where this is relevant. Data is inconsistently collected, stored, used and shared appropriately and legally. Information is not regularly available or used effectively to monitor and improve the quality of care. There is variability in the recognition, understanding and implementation of relevant quality standards, and legal requirements are not consistently understood or fulfilled. Leaders and staff have an inconsistent understanding of regulatory requirements. They do not keep adequately up-to-date or understand relevant changes. Risks are inconsistently identified or managed. Systems for managing service performance and risk are inadequate and/or are not regularly reviewed to ensure they are effective. Quality assurance arrangements are inconsistently applied or are ineffective. There are gaps in identifying improvements. Action to introduce improvements can be absent, reactive, focused on the short term or not reviewed. Information needs are not regularly reviewed. The voice of people with lived experience is not appropriately represented in decision making in the service, including strategic decisions, risk assessments or quality improvement. Engagement may be limited or absent. Business continuity plans are minimal or would not meet the needs of people using the service. Not all staff are unaware of them or how to apply them.$$
WHERE title = $$Governance and management$$;
